// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {api} from '../models';
import {history} from '../models';
import {mediasearch} from '../models';
import {parser} from '../models';
import {tmdb} from '../models';
import {tester} from '../models';

export function AcknowledgeTorrentAdmin(arg1:string):Promise<void>;

export function AutoReseedDDLFromHydracker(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number):Promise<main.AutoReseedDDLResult>;

export function AutoReseedFromHydracker(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number):Promise<main.AutoReseedResult>;

export function AutoReseedFullFromTorrent(arg1:number,arg2:number,arg3:number,arg4:number):Promise<main.AutoReseedFullResult>;

export function BuildTeamJSON(arg1:Record<string, main.RoleDef>,arg2:Array<main.TeamUser>,arg3:Record<string, string>):Promise<string>;

export function CancelAllWorkflows():Promise<void>;

export function CancelDDLHost(arg1:string):Promise<void>;

export function ChangeMyPassword(arg1:string):Promise<string>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ClearLihdlSettingsPassword(arg1:string):Promise<void>;

export function ClearSeedboxSettingsPassword(arg1:string):Promise<void>;

export function DeleteLien(arg1:number):Promise<void>;

export function DeleteMyLien(arg1:number):Promise<void>;

export function DeleteMyNzb(arg1:number):Promise<void>;

export function DeleteMyTorrent(arg1:number):Promise<void>;

export function DeleteNzb(arg1:number):Promise<void>;

export function DeleteSeedboxByHash(arg1:string):Promise<void>;

export function DeleteTorrent(arg1:number):Promise<void>;

export function DeleteTorrentAndFTP(arg1:number):Promise<main.DeleteTorrentResult>;

export function DownloadToDownloads(arg1:string,arg2:string):Promise<string>;

export function DownloadUpdate():Promise<string>;

export function FetchHydrackerAvatar():Promise<string>;

export function FetchImageBase64(arg1:string):Promise<string>;

export function FicheGetContent(arg1:number):Promise<main.FicheContent>;

export function FicheGetNfo(arg1:string,arg2:number):Promise<string>;

export function FindFirstMkvInFolder(arg1:string):Promise<string>;

export function FindHydrackerSources(arg1:number,arg2:number,arg3:number):Promise<main.FindHydrackerSourcesResult>;

export function GetConfig():Promise<config.Config>;

export function GetCurrentUser():Promise<main.AuthResult>;

export function GetDDLFilename(arg1:string):Promise<string>;

export function GetDDLFilenameByLienID(arg1:number):Promise<main.DDLResolved>;

export function GetEffectiveHydrackerURL():Promise<string>;

export function GetFileSize(arg1:string):Promise<number>;

export function GetMetaLangs():Promise<Array<api.Lang>>;

export function GetMetaQualities():Promise<Array<api.Quality>>;

export function GetMetaSubs():Promise<Array<api.Lang>>;

export function GetMyUsername():Promise<string>;

export function GetNexumIndex():Promise<main.NexumIndex>;

export function GetNzbFilenames(arg1:number):Promise<Array<main.NzbFileEntry>>;

export function GetTeamConfig():Promise<main.TeamConfig>;

export function GetUploaderStats(arg1:number):Promise<main.UploaderScanResult>;

export function GetUserProfile(arg1:string):Promise<api.User>;

export function GetVersion():Promise<string>;

export function HasLihdlSettingsPassword():Promise<boolean>;

export function HasSeedboxSettingsPassword():Promise<boolean>;

export function HashPassword(arg1:string):Promise<string>;

export function HistoryDelete(arg1:number):Promise<void>;

export function HistoryList(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<history.Entry>>;

export function HistoryStats():Promise<Record<string, number>>;

export function HydrackerGetByID(arg1:number):Promise<api.PartialTitle>;

export function HydrackerGetByTmdbID(arg1:number):Promise<api.PartialTitle>;

export function HydrackerGetLienByID(arg1:number):Promise<api.Lien>;

export function HydrackerGetLienDetailByID(arg1:number):Promise<api.LienDetail>;

export function HydrackerSearch(arg1:string):Promise<Array<api.PartialTitle>>;

export function IsHydrackerURLManaged():Promise<boolean>;

export function IsLihdlPasswordManaged():Promise<boolean>;

export function IsSeedboxPasswordManaged():Promise<boolean>;

export function IsTorrentAdminAcknowledged():Promise<boolean>;

export function IsWatching():Promise<boolean>;

export function ListCheckTorrents(arg1:boolean):Promise<Array<main.CheckTorrentEntry>>;

export function ListMyLiens(arg1:string,arg2:number):Promise<api.AdminLiensResponse>;

export function ListMyTorrents(arg1:string,arg2:number):Promise<api.AdminTorrentsResponse>;

export function ListReseedRequests(arg1:string,arg2:number,arg3:number,arg4:number):Promise<api.ReseedRequestsResponse>;

export function ListSeedboxHashes():Promise<Array<string>>;

export function ListTitlesSorted(arg1:string,arg2:number,arg3:number):Promise<api.TitlesResponse>;

export function LoginUser(arg1:string,arg2:string):Promise<main.AuthResult>;

export function Logout():Promise<void>;

export function MediaSearch(arg1:string):Promise<Array<mediasearch.SearchResult>>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenBrowser(arg1:string):Promise<void>;

export function OpenHydrackerAdmin():Promise<void>;

export function ParseFilename(arg1:string):Promise<parser.FileInfo>;

export function PostDDLWorkflow(arg1:number,arg2:number,arg3:Array<string>,arg4:Array<string>,arg5:string,arg6:string,arg7:boolean,arg8:boolean,arg9:number,arg10:number,arg11:boolean):Promise<main.DDLWorkflowResult>;

export function PostExistingTorrent(arg1:number,arg2:number,arg3:Array<string>,arg4:Array<string>,arg5:string,arg6:string,arg7:number,arg8:number,arg9:boolean):Promise<main.TorrentWorkflowResult>;

export function PostLien(arg1:number,arg2:number,arg3:Array<string>,arg4:Array<string>,arg5:string,arg6:string,arg7:number,arg8:number,arg9:boolean):Promise<api.UploadLienResult>;

export function PostNzb(arg1:number,arg2:number,arg3:Array<string>,arg4:Array<string>,arg5:string,arg6:string,arg7:number,arg8:number,arg9:boolean):Promise<api.UploadNzbResult>;

export function PostNzbWorkflow(arg1:number,arg2:number,arg3:Array<string>,arg4:Array<string>,arg5:string,arg6:string,arg7:number,arg8:number,arg9:boolean):Promise<main.NzbWorkflowResult>;

export function PostTorrent(arg1:number,arg2:number,arg3:Array<string>,arg4:Array<string>,arg5:string,arg6:string,arg7:number,arg8:number,arg9:boolean):Promise<api.UploadTorrentResult>;

export function PostTorrentWorkflow(arg1:number,arg2:number,arg3:Array<string>,arg4:Array<string>,arg5:string,arg6:string,arg7:number,arg8:number,arg9:string,arg10:boolean):Promise<main.TorrentWorkflowResult>;

export function PrepareSeasonFolder(arg1:Array<string>):Promise<string>;

export function ReadFileChunk(arg1:string,arg2:number,arg3:number):Promise<Array<number>>;

export function ReseedExecute(arg1:string,arg2:string):Promise<void>;

export function ReseedFromLihdl(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReseedPrepare(arg1:string):Promise<main.ReseedPrepareResult>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectAnyTorrentFile():Promise<string>;

export function SelectArchiveFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectMkvFile():Promise<string>;

export function SelectMkvFiles():Promise<Array<string>>;

export function SelectNzbFile():Promise<string>;

export function SelectTorrentFile():Promise<string>;

export function SetLihdlSettingsPassword(arg1:string,arg2:string):Promise<void>;

export function SetSeedboxSettingsPassword(arg1:string,arg2:string):Promise<void>;

export function SkipCurrentEpisode():Promise<void>;

export function StartWatchFolder(arg1:string):Promise<void>;

export function StopWatchFolder():Promise<void>;

export function TMDBGetByID(arg1:number,arg2:string):Promise<tmdb.Movie>;

export function TMDBGetByImdbID(arg1:string):Promise<tmdb.Movie>;

export function TMDBGetProviders(arg1:number,arg2:string):Promise<Record<string, tmdb.CountryProviders>>;

export function TMDBSearch(arg1:string):Promise<Array<tmdb.Movie>>;

export function TestFTP(arg1:string,arg2:number,arg3:string,arg4:string):Promise<tester.Result>;

export function TestHydracker(arg1:string,arg2:string):Promise<tester.Result>;

export function TestLihdl(arg1:string,arg2:string,arg3:string):Promise<tester.Result>;

export function TestModSeedbox(arg1:string,arg2:string,arg3:string):Promise<tester.Result>;

export function TestNextcloud(arg1:string,arg2:string,arg3:string):Promise<tester.Result>;

export function TestNexum():Promise<string>;

export function TestOneFichier(arg1:string):Promise<tester.Result>;

export function TestQBit(arg1:string,arg2:string,arg3:string):Promise<tester.Result>;

export function TestSeedbox(arg1:string,arg2:string,arg3:string):Promise<tester.Result>;

export function TestSendCm(arg1:string):Promise<tester.Result>;

export function TestTMDB(arg1:string):Promise<tester.Result>;

export function TestUsenet(arg1:string,arg2:number):Promise<tester.Result>;

export function TryAutoLogin():Promise<main.AuthResult>;

export function UpdateMyLien(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number):Promise<void>;

export function UpdateMyTorrent(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number):Promise<void>;

export function VerifyLihdlSettingsPassword(arg1:string):Promise<boolean>;

export function VerifySeedboxSettingsPassword(arg1:string):Promise<boolean>;
