// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcknowledgeTorrentAdmin(arg1) {
  return window['go']['main']['App']['AcknowledgeTorrentAdmin'](arg1);
}

export function AutoReseedDDLFromHydracker(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AutoReseedDDLFromHydracker'](arg1, arg2, arg3, arg4, arg5);
}

export function AutoReseedFromHydracker(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AutoReseedFromHydracker'](arg1, arg2, arg3, arg4, arg5);
}

export function AutoReseedFullFromTorrent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AutoReseedFullFromTorrent'](arg1, arg2, arg3, arg4);
}

export function BuildTeamJSON(arg1, arg2, arg3) {
  return window['go']['main']['App']['BuildTeamJSON'](arg1, arg2, arg3);
}

export function CancelAllWorkflows() {
  return window['go']['main']['App']['CancelAllWorkflows']();
}

export function CancelDDLHost(arg1) {
  return window['go']['main']['App']['CancelDDLHost'](arg1);
}

export function ChangeMyPassword(arg1) {
  return window['go']['main']['App']['ChangeMyPassword'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearLihdlSettingsPassword(arg1) {
  return window['go']['main']['App']['ClearLihdlSettingsPassword'](arg1);
}

export function ClearSeedboxSettingsPassword(arg1) {
  return window['go']['main']['App']['ClearSeedboxSettingsPassword'](arg1);
}

export function DeleteLien(arg1) {
  return window['go']['main']['App']['DeleteLien'](arg1);
}

export function DeleteMyLien(arg1) {
  return window['go']['main']['App']['DeleteMyLien'](arg1);
}

export function DeleteMyNzb(arg1) {
  return window['go']['main']['App']['DeleteMyNzb'](arg1);
}

export function DeleteMyTorrent(arg1) {
  return window['go']['main']['App']['DeleteMyTorrent'](arg1);
}

export function DeleteNzb(arg1) {
  return window['go']['main']['App']['DeleteNzb'](arg1);
}

export function DeleteSeedboxByHash(arg1) {
  return window['go']['main']['App']['DeleteSeedboxByHash'](arg1);
}

export function DeleteTorrent(arg1) {
  return window['go']['main']['App']['DeleteTorrent'](arg1);
}

export function DeleteTorrentAndFTP(arg1) {
  return window['go']['main']['App']['DeleteTorrentAndFTP'](arg1);
}

export function DownloadToDownloads(arg1, arg2) {
  return window['go']['main']['App']['DownloadToDownloads'](arg1, arg2);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function FetchHydrackerAvatar() {
  return window['go']['main']['App']['FetchHydrackerAvatar']();
}

export function FetchImageBase64(arg1) {
  return window['go']['main']['App']['FetchImageBase64'](arg1);
}

export function FicheGetContent(arg1) {
  return window['go']['main']['App']['FicheGetContent'](arg1);
}

export function FicheGetNfo(arg1, arg2) {
  return window['go']['main']['App']['FicheGetNfo'](arg1, arg2);
}

export function FindFirstMkvInFolder(arg1) {
  return window['go']['main']['App']['FindFirstMkvInFolder'](arg1);
}

export function FindHydrackerSources(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindHydrackerSources'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDDLFilename(arg1) {
  return window['go']['main']['App']['GetDDLFilename'](arg1);
}

export function GetEffectiveHydrackerURL() {
  return window['go']['main']['App']['GetEffectiveHydrackerURL']();
}

export function GetFileSize(arg1) {
  return window['go']['main']['App']['GetFileSize'](arg1);
}

export function GetMetaLangs() {
  return window['go']['main']['App']['GetMetaLangs']();
}

export function GetMetaQualities() {
  return window['go']['main']['App']['GetMetaQualities']();
}

export function GetMetaSubs() {
  return window['go']['main']['App']['GetMetaSubs']();
}

export function GetMyUsername() {
  return window['go']['main']['App']['GetMyUsername']();
}

export function GetNexumIndex() {
  return window['go']['main']['App']['GetNexumIndex']();
}

export function GetNzbFilenames(arg1) {
  return window['go']['main']['App']['GetNzbFilenames'](arg1);
}

export function GetTeamConfig() {
  return window['go']['main']['App']['GetTeamConfig']();
}

export function GetUploaderStats(arg1) {
  return window['go']['main']['App']['GetUploaderStats'](arg1);
}

export function GetUserProfile(arg1) {
  return window['go']['main']['App']['GetUserProfile'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasLihdlSettingsPassword() {
  return window['go']['main']['App']['HasLihdlSettingsPassword']();
}

export function HasSeedboxSettingsPassword() {
  return window['go']['main']['App']['HasSeedboxSettingsPassword']();
}

export function HashPassword(arg1) {
  return window['go']['main']['App']['HashPassword'](arg1);
}

export function HistoryDelete(arg1) {
  return window['go']['main']['App']['HistoryDelete'](arg1);
}

export function HistoryList(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['HistoryList'](arg1, arg2, arg3, arg4);
}

export function HistoryStats() {
  return window['go']['main']['App']['HistoryStats']();
}

export function HydrackerGetByID(arg1) {
  return window['go']['main']['App']['HydrackerGetByID'](arg1);
}

export function HydrackerGetByTmdbID(arg1) {
  return window['go']['main']['App']['HydrackerGetByTmdbID'](arg1);
}

export function HydrackerSearch(arg1) {
  return window['go']['main']['App']['HydrackerSearch'](arg1);
}

export function IsHydrackerURLManaged() {
  return window['go']['main']['App']['IsHydrackerURLManaged']();
}

export function IsLihdlPasswordManaged() {
  return window['go']['main']['App']['IsLihdlPasswordManaged']();
}

export function IsSeedboxPasswordManaged() {
  return window['go']['main']['App']['IsSeedboxPasswordManaged']();
}

export function IsTorrentAdminAcknowledged() {
  return window['go']['main']['App']['IsTorrentAdminAcknowledged']();
}

export function IsWatching() {
  return window['go']['main']['App']['IsWatching']();
}

export function ListCheckTorrents(arg1) {
  return window['go']['main']['App']['ListCheckTorrents'](arg1);
}

export function ListMyLiens(arg1, arg2) {
  return window['go']['main']['App']['ListMyLiens'](arg1, arg2);
}

export function ListMyTorrents(arg1, arg2) {
  return window['go']['main']['App']['ListMyTorrents'](arg1, arg2);
}

export function ListReseedRequests(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListReseedRequests'](arg1, arg2, arg3, arg4);
}

export function ListSeedboxHashes() {
  return window['go']['main']['App']['ListSeedboxHashes']();
}

export function ListTitlesSorted(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListTitlesSorted'](arg1, arg2, arg3);
}

export function LoginUser(arg1, arg2) {
  return window['go']['main']['App']['LoginUser'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MediaSearch(arg1) {
  return window['go']['main']['App']['MediaSearch'](arg1);
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function OpenHydrackerAdmin() {
  return window['go']['main']['App']['OpenHydrackerAdmin']();
}

export function ParseFilename(arg1) {
  return window['go']['main']['App']['ParseFilename'](arg1);
}

export function PostDDLWorkflow(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['PostDDLWorkflow'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function PostExistingTorrent(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['PostExistingTorrent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function PostLien(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['PostLien'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function PostNzb(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['PostNzb'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function PostNzbWorkflow(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['PostNzbWorkflow'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function PostTorrent(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['PostTorrent'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function PostTorrentWorkflow(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['PostTorrentWorkflow'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function PrepareSeasonFolder(arg1) {
  return window['go']['main']['App']['PrepareSeasonFolder'](arg1);
}

export function ReadFileChunk(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadFileChunk'](arg1, arg2, arg3);
}

export function ReseedExecute(arg1, arg2) {
  return window['go']['main']['App']['ReseedExecute'](arg1, arg2);
}

export function ReseedFromLihdl(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReseedFromLihdl'](arg1, arg2, arg3);
}

export function ReseedPrepare(arg1) {
  return window['go']['main']['App']['ReseedPrepare'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectAnyTorrentFile() {
  return window['go']['main']['App']['SelectAnyTorrentFile']();
}

export function SelectArchiveFile() {
  return window['go']['main']['App']['SelectArchiveFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectMkvFile() {
  return window['go']['main']['App']['SelectMkvFile']();
}

export function SelectMkvFiles() {
  return window['go']['main']['App']['SelectMkvFiles']();
}

export function SelectNzbFile() {
  return window['go']['main']['App']['SelectNzbFile']();
}

export function SelectTorrentFile() {
  return window['go']['main']['App']['SelectTorrentFile']();
}

export function SetLihdlSettingsPassword(arg1, arg2) {
  return window['go']['main']['App']['SetLihdlSettingsPassword'](arg1, arg2);
}

export function SetSeedboxSettingsPassword(arg1, arg2) {
  return window['go']['main']['App']['SetSeedboxSettingsPassword'](arg1, arg2);
}

export function SkipCurrentEpisode() {
  return window['go']['main']['App']['SkipCurrentEpisode']();
}

export function StartWatchFolder(arg1) {
  return window['go']['main']['App']['StartWatchFolder'](arg1);
}

export function StopWatchFolder() {
  return window['go']['main']['App']['StopWatchFolder']();
}

export function TMDBGetByID(arg1, arg2) {
  return window['go']['main']['App']['TMDBGetByID'](arg1, arg2);
}

export function TMDBGetByImdbID(arg1) {
  return window['go']['main']['App']['TMDBGetByImdbID'](arg1);
}

export function TMDBGetProviders(arg1, arg2) {
  return window['go']['main']['App']['TMDBGetProviders'](arg1, arg2);
}

export function TMDBSearch(arg1) {
  return window['go']['main']['App']['TMDBSearch'](arg1);
}

export function TestFTP(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestFTP'](arg1, arg2, arg3, arg4);
}

export function TestHydracker(arg1, arg2) {
  return window['go']['main']['App']['TestHydracker'](arg1, arg2);
}

export function TestLihdl(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestLihdl'](arg1, arg2, arg3);
}

export function TestModSeedbox(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestModSeedbox'](arg1, arg2, arg3);
}

export function TestNextcloud(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestNextcloud'](arg1, arg2, arg3);
}

export function TestNexum() {
  return window['go']['main']['App']['TestNexum']();
}

export function TestOneFichier(arg1) {
  return window['go']['main']['App']['TestOneFichier'](arg1);
}

export function TestQBit(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestQBit'](arg1, arg2, arg3);
}

export function TestSeedbox(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestSeedbox'](arg1, arg2, arg3);
}

export function TestSendCm(arg1) {
  return window['go']['main']['App']['TestSendCm'](arg1);
}

export function TestTMDB(arg1) {
  return window['go']['main']['App']['TestTMDB'](arg1);
}

export function TestUsenet(arg1, arg2) {
  return window['go']['main']['App']['TestUsenet'](arg1, arg2);
}

export function TryAutoLogin() {
  return window['go']['main']['App']['TryAutoLogin']();
}

export function UpdateMyLien(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateMyLien'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateMyTorrent(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateMyTorrent'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function VerifyLihdlSettingsPassword(arg1) {
  return window['go']['main']['App']['VerifyLihdlSettingsPassword'](arg1);
}

export function VerifySeedboxSettingsPassword(arg1) {
  return window['go']['main']['App']['VerifySeedboxSettingsPassword'](arg1);
}
